Stumeet/STUMEET-SERVER

- .github/CODEOWNERS
- 리뷰어를 자동으로 등록하고 싶어요..
- github에서 제공하는 CODEOWNERS를 통해 해결
> [STMT-6] :memo: 리뷰어 자동 등록을 위한 CODEOWNERS 추가

- .github/CODEOWNERS
- 리뷰어를 자동으로 등록하고 싶어요..
- github에서 제공하는 CODEOWNERS를 통해 해결
> [STMT-6] :memo: 리뷰어 자동 등록을 위한 CODEOWNERS 추가 (#5)

- .github/workflows/dnrule.yml
- D-n Rule 적용시 불편함을 감소하기 위해 D-Day를 자동 감소시키고 싶어요 😢 
- 매일 00시 00분 마다 D-n 태그를 1씩 감소시키고 D-0에 도달시 더이상 감소시키지 않도록 만들었습니다.
- 자세한 내용은 [해당 레포](https://github.com/zxcv9203/dnRule)를 참조해주시면 좋을 것 같아요
> [STMT-6] :hammer: D-n rule D-day 자동 감소를 위한 스크립트 추가

- src/main/java/com/stumeet/server/account/adapter/in/web/AccountController.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountJpaEntity.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountMapper.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountPersistenceAdapter.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/JpaAccountRepository.java
- src/main/java/com/stumeet/server/account/application/port/in/AccountUseCase.java
- src/main/java/com/stumeet/server/account/application/port/in/SignupCommand.java
- src/main/java/com/stumeet/server/account/application/port/out/AccountPort.java
- src/main/java/com/stumeet/server/account/application/service/AccountService.java
- src/main/java/com/stumeet/server/account/domain/Account.java
- src/main/java/com/stumeet/server/common/annotation/PersistenceAdapter.java
- src/main/java/com/stumeet/server/common/annotation/UseCase.java
- src/main/java/com/stumeet/server/common/annotation/WebAdapter.java
- 개발 시 사용할 패키지 구조 정의
- `만들면서 배우는 클린아키텍처`를 기준으로 헥사고날 아키텍처 형태로 작성
- 해당 패키지 구조가 잘 이해되는지 확인 부탁드립니다.
구조는 다음과 같습니다.
```
.
├── account : 비즈니스 요구사항을 의미합니다. 여기서는 사용자 계정을 의미하는 account 관련 비즈니스 요구사항을 의미합니다.
│   ├── adapter :  외부 -> 내부, 내부 -> 외부로의 진입점을 작성하는 패키지입니다.
│   │   ├── in : 외부 -> 내부 진입점
│   │   │   └── web : 웹 통신 관련 패키지입니다. 여기서는 REST API를 이용합니다.
│   │   │       └── AccountController.java : 요청을 받기위한 Controller 클래스입니다.
│   │   └── out : 내부 -> 외부 진입점
│   │       └── persistence : 데이터 영속화 관련 패키지입니다. 여기서는 RDB를 이용합니다.
│   │           ├── AccountJpaEntity.java : 데이터 영속화에 사용되는 JPA Entity 입니다.
│   │           ├── AccountMapper.java : 도메인과 JPA를 매핑할 때 사용하는 클래스입니다.
│   │           ├── AccountPersistenceAdapter.java : DB에 접근하기 위한 로직을 작성하는 클래스입니다. (Repository로 생각하시면 됩니다.)
│   │           └── …
```
> [STMT-6] :building_construction: 헥사고날 아키텍처 패키지 구조 예시 작성

- .github/CODEOWNERS
- .github/workflows/dnrule.yml
- src/main/java/com/stumeet/server/account/adapter/in/web/AccountController.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountJpaEntity.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountMapper.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/AccountPersistenceAdapter.java
- src/main/java/com/stumeet/server/account/adapter/out/persistence/JpaAccountRepository.java
- src/main/java/com/stumeet/server/account/application/port/in/AccountUseCase.java
- src/main/java/com/stumeet/server/account/application/port/in/SignupCommand.java
- src/main/java/com/stumeet/server/account/application/port/out/AccountPort.java
- src/main/java/com/stumeet/server/account/application/service/AccountService.java
- src/main/java/com/stumeet/server/account/domain/Account.java
- src/main/java/com/stumeet/server/common/annotation/PersistenceAdapter.java
- src/main/java/com/stumeet/server/common/annotation/UseCase.java
- src/main/java/com/stumeet/server/common/annotation/WebAdapter.java
https://github.com/Stumeet/STUMEET-SERVER/pull/7
> [STMT-6] :hammer: D-n rule D-day 자동 감소를 위한 스크립트 추가 (#7)

- build.gradle
- src/main/java/com/stumeet/server/common/annotation/StorageAdapter.java
- src/main/java/com/stumeet/server/common/config/AwsS3Config.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/common/util/FileUtil.java
- src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
- src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- S3를 활용한 사용자 프로필 이미지 업로드 기능 구현
* :heavy_plus_sign: [STMT-146] S3 의존성 추가
- aws 의존성 간의 버전 호환을 위한 `software.amazon.awssdk:bom:2.21.1` 추가
* :wrench: [STMT-146] S3 환경변수 설정
* :sparkles: [STMT-146] 저장소 adapter를 위한 어노테이션 구현
* :sparkles: [STMT-146] S3 사용자 프로필 이미지 업로드 기능 구현
- 스터디 이미지 리스트 업로드는 아직 구현되지 않았습니다.
[STMT-146]: https://stumeet.atlassian.net/browse/STMT-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STMT-146]: https://stumeet.atlassian.net/browse/STMT-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STMT-146]: https://stumeet.atlassian.net/browse/STMT-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STMT-146]: …
> ✨ [STMT-146] S3를 활용한 사용자 프로필 이미지 업로드 기능 구현 (#29)

- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberValidApi.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaMemberRepository.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberValidUseCase.java
- src/main/java/com/stumeet/server/member/application/port/out/MemberQueryPort.java
- src/main/java/com/stumeet/server/member/application/service/MemberValidService.java
- 회원가입중 닉네임 중복 체크 여부 확인
- 닉네임 중복 체크 API 구현
> :sparkles: [STMT-146] 닉네임 중복 체크 기능 구현[

- src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
- src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- 최초 로그인시 필요한 데이터를 받도록 구현
- 이메일 정보와 닉네임 정보, 지역, 분야 정보를 추가로 받도록 구현
- 분야의 경우 별도로 대분류 / 소분류 형태로 받기 이전까지는 문자열로 받도록 구현했습니다.
> ✨ [STMT-146] 최초 로그인시 회원가입 기능 구현

- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/file/application/port/in/FileUploadUseCase.java
- src/main/java/com/stumeet/server/file/application/service/FileUploadService.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberValidApi.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/JpaMemberRepository.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberValidUseCase.java
- src/main/java/com/stumeet/server/member/application/port/out/MemberQueryPort.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/main/java/com/stumeet/server/member/application/service/MemberValidService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- 닉네임 중복 체크 기능
- 최초 로그인시 회원가입 기능
- 이에 대응하는 API 구현 #33 #34
> ✨ [STMT-146] 최초 가입시 사용되는 닉네임 중복 체크 기능, 추가 정보 입력 기능 API 구현

- src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
- src/main/java/com/stumeet/server/common/auth/handler/JwtLogoutHandler.java
- src/main/java/com/stumeet/server/common/auth/handler/JwtLogoutSuccessHandler.java
- 로그아웃 기능 구현
- 인증정보에 담긴 Access Token 정보를 기준으로 Redis에 저장된 RefreshToken을 삭제하도록 구현했습니다.
- Spring Security의 LogoutFilter를 Override해서 작성했습니다.
> :sparkles: [STMT-146] 로그아웃 기능 구현

- src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
- src/main/java/com/stumeet/server/common/auth/handler/JwtLogoutHandler.java
- src/main/java/com/stumeet/server/common/auth/handler/JwtLogoutSuccessHandler.java
> :sparkles: [STMT-146] 로그아웃 기능 구현 (#37)

- build.gradle
- API 문서 경로가 잘못되어 보이지 않는 현상
- 경로를 수정하여  문제 해결
> :bug: [STMT-146] 잘못 작성한 테스트 경로 수정

- build.gradle
- 잘못 작성한 테스트 경로 수정
-  #44 참고 부탁드립니다.
> :bug: [STMT-146] 잘못 작성한 테스트 경로 수정 (#44)

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilter.java
- src/main/java/com/stumeet/server/common/auth/handler/InvalidAuthenticationFailureHandler.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- 소셜 로그인 시 인증 실패에 대한 API 문서화 및 테스트 코드 작성
- 테스트 코드 작성 완료
> :white_check_mark: [STMT-146] 소셜 로그인시 인증 실패에 대한 상황에 대한 테스트 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilter.java
- src/main/java/com/stumeet/server/common/auth/handler/InvalidAuthenticationFailureHandler.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
> :white_check_mark: [STMT-146] 소셜 로그인시 인증 실패에 대한 상황에 대한 테스트 추가 (#46)

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- 토큰 재발급 API 문서화
- 액세스 토큰 만료시 토큰 재발급 실패 버그 픽스
- 리프레시 토큰에서 유저정보를 얻어올 수 있도록 변경
- 토큰 재발급 성공 테스트 API 문서화 완료
> ✅ [STMT-146] 토큰 재발급 성공 테스트 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
> ✅ [STMT-146] 토큰 재발급 성공 테스트 추가 (#48)

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- src/test/java/com/stumeet/server/template/ApiTest.java
> ✅ [STMT-146] 토큰 재발급 성공 테스트 추가 (#50)

- .github/workflows/ci.yml
- PR시 해당 코드가 정상 동작하는지 CI를 추가하고 싶어요
- PR시 테스트 코드를 실행하는 로직 추가
> :wrench: [STMT-146] PR시 테스트를 실행하도록 Workflow 추가

- .github/workflows/ci.yml
> :wrench: [STMT-146] PR시 테스트를 실행하도록 Workflow 추가 (#52)

- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/OAuthLoginJpaEntity.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/JpaProfessionRepository.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionJpaEntity.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceAdapter.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceMapper.java
- src/main/java/com/stumeet/server/profession/application/port/in/ProfessionQueryUseCase.java
- src/main/java/com/stumeet/server/profession/application/port/out/ProfessionQueryPort.java
- src/main/java/com/stumeet/server/profession/application/service/ProfessionQueryService.java
- src/main/java/com/stumeet/server/profession/domain/Profession.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1.1__insert_profession_data.sql
- src/main/resources/db/migration/V1__init.sql
- src/test/resources/application.yml
> ✨ [STMT-146] 분야 정보를 관리하는 도메인 정의 (#54)

- src/main/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApi.java
- src/main/java/com/stumeet/server/profession/adapter/in/web/response/ProfessionResponse.java
- src/main/java/com/stumeet/server/profession/adapter/in/web/response/ProfessionResponses.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceAdapter.java
- src/main/java/com/stumeet/server/profession/application/port/in/ProfessionQueryUseCase.java
- src/main/java/com/stumeet/server/profession/application/port/out/ProfessionQueryPort.java
- src/main/java/com/stumeet/server/profession/application/service/ProfessionQueryService.java
- DB에 저장된 분야 정보를 조회하고 싶어요
- 분야 정보를 조회하는 API 구현
> :sparkles: [STMT-146] 분야 정보를 전부 조회하는 API 구현

- src/main/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApi.java
- src/main/java/com/stumeet/server/profession/adapter/in/web/response/ProfessionResponse.java
- src/main/java/com/stumeet/server/profession/adapter/in/web/response/ProfessionResponses.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceAdapter.java
- src/main/java/com/stumeet/server/profession/application/port/in/ProfessionQueryUseCase.java
- src/main/java/com/stumeet/server/profession/application/port/out/ProfessionQueryPort.java
- src/main/java/com/stumeet/server/profession/application/service/ProfessionQueryService.java
> :sparkles: [STMT-146] 분야 정보를 전부 조회하는 API 구현 (#56)

- src/docs/asciidoc/index.adoc
- src/test/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApiTest.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- 분야 정보 조회 API 문서화 및 테스트 코드 작성
- 분야 정보 조회 테스트 코드 작성
> :white_check_mark: [STMT-146] 분야 정보 조회 API 테스트 코드 추가

- src/docs/asciidoc/index.adoc
- src/test/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApiTest.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
> :white_check_mark: [STMT-146] 분야 정보 조회 API 테스트 코드 추가 (#58)

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/common/token/repository/RefreshTokenRepositoryImpl.java
- src/main/java/com/stumeet/server/common/token/service/RefreshTokenService.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
> ✅ [STMT-146] 토큰 재발급 API 실패 응답 테스트 작성 (#62)

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberValidApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- 닉네임 유효성 검사 API 문서화 및 테스트 코드 작성
-  닉네임 유효성 검사 API 문서화 및 테스트 코드 작성
> :white_check_mark: [STMT-146] 닉네임 유효성 검사 API 테스트 코드 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberValidApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
> :white_check_mark: [STMT-146] 닉네임 유효성 검사 API 테스트 코드 추가 (#64)

- src/test/java/com/stumeet/server/common/auth/filter/LogoutFilterTest.java
> :bug: [STMT-146] 로그아웃 API 테스트시 Redis 컨테이너를 띄우도록 변경 (#68)

- build.gradle
- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/handler/ForbiddenAccessHandler.java
- src/main/java/com/stumeet/server/common/config/AwsS3Config.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/test/java/com/stumeet/server/helper/TestAwsS3Config.java
- src/test/java/com/stumeet/server/helper/WithMockMember.java
- src/test/java/com/stumeet/server/helper/WithMockMemberSecurityContextFactory.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberValidApiTest.java
- src/test/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/template/ApiTest.java
> ✅ [STMT-146] 최초 로그인 시 회원가입 API 테스트 코드 작성 (#70)

- .github/workflows/ci.yml
- .github/workflows/ci_trigger.yml
- fork repository는 CI 워크플로우 실행 시에 origin repository의 private github action secret을 읽어오지 못함
- dev에 PR을 올리면 CI trigger 워크플로우가 실행되고, CI trigger 워크플로우가 실행되면 CI 워크플로우가 실행되도록 수정
- origin repository가 실행하는 워크플로우이므로 secret 사용 가능
- 참고 자료
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
https://stackoverflow.com/questions/67247752/how-to-use-secret-in-pull-request-review-similar-to-pull-request-target
> 🔨 [STMT-6] fork repository를 위한 CI workflow 구축

- src/main/java/com/stumeet/server/member/adapter/in/web/response/MemberProfileResponse.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
- src/main/java/com/stumeet/server/member/application/port/in/mapper/MemberUseCaseMapper.java
- src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
- src/main/java/com/stumeet/server/member/domain/MemberLevel.java
- src/main/java/com/stumeet/server/member/domain/MemberTier.java
- src/main/resources/db/migration/V1.3__modify_column_rank_to_tier.sql
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberProfileApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/resources/db/setup.sql
>  :bug: [STMT-146] 멤버 레벨을 표현하기 위한 rank 칼럼의 DB 예약어로 인한 insert 쿼리 실패 버그 해결

- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberJpaEntity.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceMapper.java
- src/main/java/com/stumeet/server/studymember/domain/StudyMember.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1.7__add_study_member_table.sql
- src/test/resources/application.yml
- 스터디 멤버 관련 기능 구현을 위한 도메인 정의
- 도메인 정의 및 스키마 작성 완료했습니다.
- 스터디 멤버에서 성취도 부분을 제거했습니다. 제거한 이유는 활동의 추가 및 완료에 대해 계속해서 Update 쿼리가 발생하기도 하고 변경이 잦을 수 있는 부분이라 생각해 DB 칼럼으로 두는 의미가 크게 없다고 판단했습니다.
> :sparkles: [STMT-220] 스터디 멤버 도메인 정의 및 스키마 추가

- .github/workflows/ci-cd.yml
- 변경 사항을 바로바로 테스트하고 싶어요
- dev 브랜치에 push가 발생할 경우 배포하도록 변경
> 👷 [STMT-6] dev 브랜치에도 CI/CD 파이프라인이 실행되도록 변경

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/common/response/SuccessCode.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustom.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImpl.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberLeaveUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberValidationUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveService.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
- src/main/java/com/stumeet/server/studymember/domain/exception/NotStudyAdminException.java
- src/test/java/com/stumeet/server/stub/StudyMemberStub.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApiTest.java
- src/test/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveServiceTest.java
- 스터디 멤버 강퇴 기능 구현
- 스터디 멤버 강퇴 기능을 구현했습니다.
> ✨ [STMT-192] 관리자 스터디 강퇴 기능 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/common/response/SuccessCode.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberJoinApi.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/mapper/StudyMemberJoinWebAdapterMapper.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberValidationUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberJoinService.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
- src/main/java/com/stumeet/server/studymember/domain/exception/AlreadyStudyJoinMemberException.java
- src/main/java/com/stumeet/server/studymember/domain/exception/NotStudyAdminException.java
- src/main/java/com/stumeet/server/studymember/domain/exception/StudyMemberNotJoinedException.java
- src/test/java/com/stumeet/server/stub/StudyMemberStub.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberJoinApiTest.java
- src/test/java/com/stumeet/server/studymember/application/service/StudyMemberJoinServiceTest.java
- src/test/resources/db/setup.sql
- 스터디 가입 API 구현
- 스터디 가입 유즈케이스를 이용하여 구현했습니다.
- 유즈케이스에 이미 가입되었을 경우 가입을 막는 방어로직이 없어 추가했습니다.
> ✨ [STMT-171] 스터디 가입 API 구현

- src/main/java/com/stumeet/server/common/util/TimeProvider.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
- src/main/java/com/stumeet/server/study/application/port/out/StudyCommandPort.java
- src/main/java/com/stumeet/server/study/application/service/StudyFinishService.java
- src/main/java/com/stumeet/server/study/domain/Study.java
- src/main/java/com/stumeet/server/study/domain/StudyPeriod.java
> ♻️ [STMT-169] 스터디 완료 기능 리뷰 반영

- src/docs/asciidoc/index.adoc
- src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
- 가입한 스터디 리스트 조회 API 명세서를 추가했습니다.
> 📝 [STMT-268] 가입한 스터디 리스트 조회 API 명세서 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/ActivityDeleteApi.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityImagePersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityParticipantPersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityPersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityImageRepository.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityParticipantRepository.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityRepository.java
- src/main/java/com/stumeet/server/activity/application/port/in/ActivityAuthorityValidationUseCase.java
- src/main/java/com/stumeet/server/activity/application/port/in/ActivityDeleteUseCase.java
- src/main/java/com/stumeet/server/activity/application/port/in/command/ActivityDeleteCommand.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityAuthorValidationPort.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityDeletePort.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityImageCommandPort.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityParticipantCommandPort.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityAuthorityValidationService.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityDeleteService.java
- src/main/java/com/stumeet/server/activity/domain/exception/ActivityManagementAccessDeniedException.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/file/application/port/in/FileDeleteUseCase.java
- src/main/java/com/stumeet/server/file/application/service/FileDeleteService.java
- src/main/java/com/stumeet/server/study/application/port/in/ActivityImageDeleteUseCase.java
- src/main/java/com/stumeet/server/study/application/port/in/ActivityParticipantDeleteUseCase.java
- src/main/java/com/stumeet/server/study/application/service/ActivityImageDeleteService.java
- src/main/java/com/stumeet/server/study/application/service/ActivityParticipantDeleteService.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityDeleteApiTest.java
- src/test/resources/db/setup.sql
- 스터디의 딘일 활동을 삭제하는 API를 구현했습니다.
> [STMT-273] 활동 삭제 API 구현

- build.gradle
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- 타임존이 Asia/Seoul로 제대로 변경되지 않았습니다.
- 문법 오류를 수정하여 로컬에서 테스트했을 때 작동하였습니다.
> [STMT-165] 서버 타임존 변경 에러 수정

- src/docs/asciidoc/index.adoc
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityUpdateApiTest.java
- src/test/java/com/stumeet/server/stub/ActivityStub.java
> ✨ [STMT-263] 활동 수정 API 명세서 작성

- src/docs/asciidoc/index.adoc
- src/test/java/com/stumeet/server/activity/adapter/in/ParticipantStatusUpdateApiTest.java
멤버 상태 변경 API 테스트 케이스 및 명세서를 작성했습니다.
> ✅ [STMT-264] 멤버 상태 변경 API 테스트 케이스 및 명세서 작성

- src/test/java/com/stumeet/server/study/adapter/in/web/StudyCreateApiTest.java
스터디 생성 반복 유형 종류 명세서 설명을 보강했습니다.
반복유형: `DAILY`, `WEEKLY`, `MONTHLY`
> :memo: [STMT-165] 스터디 생성 반복 유형 종류 명세서 설명 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/studymember/adapter/in/web/AdminDelegationApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/AdminManagementAdapter.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
- src/main/java/com/stumeet/server/studymember/application/port/in/AdminDelegationUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/out/AdminManagementPort.java
- src/main/java/com/stumeet/server/studymember/application/service/AdminDelegationService.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/AdminDelegationApiTest.java
스터디 내에서 관리자를 위임하는 API를 구현했습니다.
- 유효성 검사
- 요청자가 관리자인지 검증
- 위임 대상자가 스터디 멤버인지 검증
> ✨ [STMT-266] 관리자 위임 API 구현

- src/docs/asciidoc/index.adoc
이전 스터디 완료 API 구현 시 누락했던 명세서 작성을 완료했습니다.
> :memo: [STMT-169] 스터디 완료 API 명세서 작성

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyRepository.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
- src/main/java/com/stumeet/server/study/application/port/in/StudyValidationUseCase.java
- src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyUseCaseMapper.java
- src/main/java/com/stumeet/server/study/application/port/out/StudyQueryPort.java
- src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
- src/main/java/com/stumeet/server/study/application/service/StudyValidationService.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/LegacyStudyHideApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberJpaEntity.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/mapper/StudyMemberPersistenceMapper.java
- src/main/java/com/stumeet/server/studymember/application/port/in/LegacyStudyHideUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberUpdatePort.java
- src/main/java/com/stumeet/server/studymember/application/service/LegacyStudyHideService.java
- src/main/java/com/stumeet/server/studymember/domain/StudyMember.java
- src/main/resources/db/migration/V1.8__add_legacy_hidden_column_to_study_member_table.sql
- src/test/java/com/stumeet/server/stub/StudyStub.java
- src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/LegacyStudyHideApiTest.java
- src/test/resources/db/setup.sql
- 레거시 스터디 목록 조회 API
- 레거시 스터디 숨김 처리 API
숨김 여부를 저장하기 위해 레거시 스터디 테이블을 추가하는 것과 study member 테이블에 속성을 추가하는 것을 고려했는데, 
테이블을 추가해야할 정도의 확장 가능성이 없다고 판단하여 기존 스터디 멤버 테이블에 레거시 스터디 숨김 여부 플래그 속성을 포함했습니다.
> ✨ [STMT-258] 레거시 스터디 목록 조회 및 레거시 스터디 숨김 처리 API 구현

- build.gradle
- src/main/java/com/stumeet/server/ServerApplication.java
- src/main/java/com/stumeet/server/batch/domain/member/Device.java
- src/main/java/com/stumeet/server/batch/domain/member/Member.java
- src/main/java/com/stumeet/server/batch/domain/member/internal/MemberScheduleNotificationProcessor.java
- src/main/java/com/stumeet/server/batch/domain/study/Activity.java
- src/main/java/com/stumeet/server/batch/domain/study/ActivityParticipant.java
- src/main/java/com/stumeet/server/batch/domain/study/Study.java
- src/main/java/com/stumeet/server/batch/dto/Notification.java
- src/main/java/com/stumeet/server/batch/job/notification/ScheduleNotificationJobConfig.java
- src/main/java/com/stumeet/server/batch/repository/ActivityRepository.java
- src/main/java/com/stumeet/server/batch/repository/MemberRepository.java
- src/main/java/com/stumeet/server/batch/runner/JobRunner.java
- src/main/java/com/stumeet/server/common/config/DataSourceConfig.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/NotificationLogRepository.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/entity/NotificationLogJpaEntity.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1.14__create_notification_log_table.sql
- src/test/java/com/stumeet/server/activity/application/service/ActivityParticipantJpaEntityQueryFacadeTest.java
- src/test/resources/application.yml
캘린더 기준 할 일이 있다면 매일 아침 9시에 사용자에게 알림을 전송하는 기능을 구현했습니다.
- Spring Batch를 사용하여 할일이 있는 멤버를 쿼리하고, 해당 내용으로 알림을 만들어 전송합니다.
- Spring Scheduler를 사용하여 매일 오전 9시에 해당 job을 실행합니다.
1. Reader에서 활동 테이블과 조인하여 오늘 기준 할일이 있는 멤버를 조회합니다.
(`모임` 활동의 경우 시작일 기준, `과제` 활동의 경우 종료일 기준)
2. Processor에서 해당 멤버의 오늘 활동 목록으로 알림 인스턴스를 생성합니다.
3. Writer에서 생성된 알림을 전송하고, 알림 기록을 남깁니다.
- Spring Batch Jpa Sample
https://github.com/spring-projects/spring-batch/blob/main/spring-batch-samples/src/main/java/org/springframework/batch/samples/jpa/JpaRepositoryJobConfiguration.java
- Spring Batch 5 Baeldung
https://www.baeldung.com/spring-boot-spring-batch
> ✨ [STMT-299] 정기 캘린더 스케줄 알림 기능 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/domain/model/AssignmentStatus.java
- src/main/java/com/stumeet/server/activity/domain/model/MeetStatus.java
- src/test/resources/db/setup.sql
> 🩹 [STMT-264] 활동 상태 정보 수정

- build.gradle
- src/main/java/com/stumeet/server/batch/adapter/persistence/mapper/NotificationLogPersistenceMapper.java
- src/main/java/com/stumeet/server/batch/adapter/persistence/repository/ActivityRepository.java
- src/main/java/com/stumeet/server/batch/adapter/persistence/repository/MemberRepository.java
- src/main/java/com/stumeet/server/batch/adapter/persistence/repository/NotificationLogRepository.java
- src/main/java/com/stumeet/server/batch/domain/member/NotificationLog.java
- src/main/java/com/stumeet/server/batch/domain/member/internal/MemberScheduleNotificationProcessor.java
- src/main/java/com/stumeet/server/batch/job/notification/ScheduleNotificationJobConfig.java
- src/main/java/com/stumeet/server/common/config/AwsS3Config.java
- src/main/java/com/stumeet/server/common/config/AwsSQSConfig.java
- src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
- src/main/java/com/stumeet/server/notification/adapter/out/notification/SQSNotificationAdapter.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/JpaNotificationLogRepository.java
- src/main/java/com/stumeet/server/notification/application/port/out/NotificationQueuePort.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1.13__create_report_table.sql
- src/main/resources/db/migration/V1.15__create_review_related_tables.sql
- src/main/resources/db/migration/V1.15__create_review_table.sql
- src/main/resources/db/migration/V1.16__create_review_tag_usage_table.sql
- src/test/resources/application.yml
전송하려는 알림의 수가 많아질 경우 현재 서버 컴퓨터로 사용중인 AWS EC2의 리소스와 네트워크 대역폭이 부족할 수 있을 것이라 예측되었습니다.
- 정기 알림 10분 전에 batch job을 통해 AWS SQS에 메시지를 적재합니다.
- EventBridge를 통해 특정 시간에 AWS Lambda를 트리거하여 멤버에게 알림을 전송합니다.
- 위 코드는 job의 writer에서 SQS로 메시지를 전송하는 기능을 구현했습니다.
> ✨ [STMT-299] Batch Job으로 특정 시간에 정기 알림을 AWS SQS에 메시지로 적재하는 기능 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/review/adapter/out/persistence/JpaReviewTagRepository.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/ReviewPersistenceAdapter.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/dto/ReviewTagCountDto.java
- src/main/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApi.java
- src/main/java/com/stumeet/server/review/adapter/out/web/dto/ReviewTagStatsResponse.java
- src/main/java/com/stumeet/server/review/application/port/in/ReviewQueryUseCase.java
- src/main/java/com/stumeet/server/review/application/port/out/ReviewQueryPort.java
- src/main/java/com/stumeet/server/review/application/service/ReviewQueryService.java
- src/test/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApiTest.java
멤버의 리뷰 태그 통계를 조회하는 API를 구현했습니다.
> ✨ [STMT-308] 멤버 리뷰 태그 통계 조회 API 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/response/ActivityListBriefResponses.java
- src/main/java/com/stumeet/server/activity/adapter/in/response/ActivityListDetailedPageResponses.java
- src/main/java/com/stumeet/server/activity/application/port/in/mapper/ActivityUseCaseMapper.java
- src/main/java/com/stumeet/server/activity/application/port/in/mapper/PageInfoUseCaseMapper.java
- src/main/java/com/stumeet/server/batch/adapter/persistence/mapper/NotificationLogPersistenceMapper.java
- src/main/java/com/stumeet/server/batch/domain/member/NotificationLog.java
- src/main/java/com/stumeet/server/common/exception/model/FormatConversionException.java
- src/main/java/com/stumeet/server/common/model/PageInfoResponse.java
- src/main/java/com/stumeet/server/notification/adapter/out/mapper/JsonToMapConverter.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/JpaNotificationLogRepository.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/NotificationLogPersistenceAdapter.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/entity/NotificationLogJpaEntity.java
- src/main/java/com/stumeet/server/notification/adapter/out/web/NotificationLogQueryApi.java
- src/main/java/com/stumeet/server/notification/adapter/out/web/dto/NotificationLogResponse.java
- src/main/java/com/stumeet/server/notification/adapter/out/web/dto/NotificationLogResponses.java
- src/main/java/com/stumeet/server/notification/application/port/in/NotificationLogQueryUseCase.java
- src/main/java/com/stumeet/server/notification/application/port/out/NotificationLogQueryPort.java
- src/main/java/com/stumeet/server/notification/application/service/NotificationLogQueryService.java
- src/test/java/com/stumeet/server/notification/adapter/out/web/NotificationLogQueryApiTest.java
- src/test/resources/db/setup.sql
멤버의 알림 기록 목록을 조회하는 API를 구현했습니다.
> ✨ [STMT-311] 멤버 알림 기록 목록 조회 API 구현

- src/main/java/com/stumeet/server/activity/application/service/ParticipantStatusUpdateService.java
- src/main/java/com/stumeet/server/member/adapter/out/event/handler/MemberLevelUpAlertHandler.java
- src/main/java/com/stumeet/server/member/adapter/out/event/model/MemberLevelUpAlertEvent.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberLevelUseCase.java
- src/main/java/com/stumeet/server/member/application/service/MemberLevelService.java
- src/main/java/com/stumeet/server/member/domain/MemberLevel.java
- src/main/java/com/stumeet/server/member/domain/MemberTier.java
- src/main/java/com/stumeet/server/notification/application/port/in/SendUserLevelUpAlertUseCase.java
- src/main/java/com/stumeet/server/notification/application/service/SendNotificationService.java
- src/main/java/com/stumeet/server/review/application/service/ReviewRegisterService.java
- src/main/java/com/stumeet/server/study/application/service/StudyCreateService.java
- src/main/java/com/stumeet/server/studymember/application/service/GrapePraiseSendService.java
- src/test/java/com/stumeet/server/member/domain/MemberTierTest.java
- 경험치 획득 및 레벨업
- 레벨 업 알림
- 멤버 레벨 서비스를 구현하여 경험치를 획득하고, 레벨업 여부를 판단하여 알림을 보내는 기능을 구현했습니다.
- 레벨 업 알림은 스프링 이벤트 핸들러를 사용하여 비동기로 전송되도록 구현했습니다.
> ✨ [STMT-315] 멤버 레벨 업 및 레벨 업 알림

- src/main/java/com/stumeet/server/batch/adapter/persistence/repository/StudyMemberRepository.java
- src/main/java/com/stumeet/server/batch/domain/study/Study.java
- src/main/java/com/stumeet/server/batch/domain/study/StudyMember.java
- src/main/java/com/stumeet/server/batch/job/notification/GrapeStatusResetJobConfig.java
- src/main/java/com/stumeet/server/batch/job/notification/ScheduleNotificationJobConfig.java
- src/main/java/com/stumeet/server/batch/runner/JobRunner.java
- 일주일에 한번 포도알을 얻을 수 있다는 문제
- 스터디의 시작일 요일에 스터디 멤버의 포도알 전송 여부를 초기화하는 배치 작업을 구현
> ✨ [STMT-318] 포도알 리셋 배치 구현
