Stumeet/STUMEET-SERVER

- src/main/java/com/stumeet/server/common/config/AuditConfig.java
- src/main/java/com/stumeet/server/common/model/BaseTimeEntity.java
- 공통적으로 사용되는 생성 시간, 수정 시간을 중복해서 작성해야는 문제가 존재
- JPA Auditing을 통해 생성 시간, 수정 시간을 자동으로 감지하고 이를 추상 클래스로 만들어서 상속하여 중복 코드를 줄일 수 있게 했습니다.
> [STMT-151] :sparkles: 공통적으로 사용되는 생성 시간, 수정 시간 추가를 위한 추상 클래스 구현

- .github/workflows/github-actions.yml
- build.gradle
- origin/main에 push 발생 시 자동으로 ec2 인스턴스에 배포되도록 CI/CD 구축
- Secret repository environment variable을 사용하여 보안적으로 이슈가 있는 정보(i.e. AWS EC2 시크릿 키)를 저장하고, 안전하게 사용하였습니다.
- stumeet.shop 도메인을 구매해 DNS를 설정했습니다.
- gradle을 caching하여 빌드 시간을 향상시켰습니다.
- CI/CD 중 도커 컨테이너 생성 시 포트 8080을 내부 포트 8080으로 바인딩하여 nginx로 하여금 stumeet server에게 http://127.0.0.1:8080를 통해 패킷을 전달하도록 하였습니다.
- 동작 테스트 목적으로 생성되어 남겨져 있던 다수의 텍스트들을  수정하였습니다.
- CD시, 기존에 실행되던 컨테이너가 중지되고 삭제되는 명령문을 넣었습니다.
- 컨테이너 생성 시 네이밍을 하여 식별에 용이하도록 하였습니다.
nginx의 `default.config` 파일의 경우 아래와 같이 작성하였습니다.
```
server{
server_name stumeet.shop;
location / {
proxy_pass http://127.0.0.1:8080;
}
listen [::]:443 ssl ipv6only=on; #managed by Certbot
listen 443 ssl; #managed by Certbot
ssl_certificate /etc/letsencrypt/live/stumeet.shop/fullchain.pem; #managed by Certbot …
```
> [STMT-6] 👷 CI/CD를 위한 github-actions 추가

- .github/workflows/ci-cd.yml
- .gitignore
- CI/CD를 위한 환경 변수 secret을 서버 인스턴스에 주입하는 코드 작성
- CI/CD 워크플로우를 관장하는 ci-cd.yml에 github action secret을 가져와 파일을 생성하는 코드를 추가했습니다.
- 워크플로우의 기능을 명시하기 위해 github-actions.yml 파일의 이름을 ci-cd.yml으로 변경했습니다.
- github action secret에 ENV 변수를 생성했습니다.
- application-secret.yml 파일을 생성했습니다. 필수요소 작성 후 공유 예정입니다.
> [STMT-6] :construction_worker: CI-CD workflow 수정 - 환경변수 설정 (#17)

- src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthClient.java
- src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthFeignClient.java
- src/main/java/com/stumeet/server/common/client/oauth/kakao/model/KakaoUserProfileResponse.java
- src/main/java/com/stumeet/server/common/client/oauth/model/OAuthUserProfileResponse.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
- src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
- 소셜 로그인은 인증만 진행하도록 변경되었습니다
- 카카오 로그인시 카카오 유저 정보를 받아오는 부분을 제거하고 토큰의 유효성만 체크하는 API를 호출하도록 변경했습니다.
> [STMT-146] :sparkles: 카카오 로그인시 카카오 유저 정보를 가져오지 않도록 변경

- src/main/java/com/stumeet/server/common/auth/filter/JwtAuthenticationFilter.java
- src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
- src/main/java/com/stumeet/server/common/client/oauth/OAuthClient.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/AppleOAuthClient.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/AppleOAuthFeignClient.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/model/ApplePublicKeyResponses.java
- src/main/java/com/stumeet/server/common/client/oauth/kakao/KakaoOAuthClient.java
- src/main/java/com/stumeet/server/common/util/JwtUtil.java
- 로그인시 애플 로그인을 지원하도록 구현
- OAuthClient를 구현하는 구현체들을 빈 이름, 구현 객체와 같은 형식으로 Map 형태로 저장해서 provider에 따라 실행되는 로직이 바뀌도록 변경
- 애플의 Public Key 목록을 받아와서 id_token이 유효한지 확인하는 로직 추가
> [STMT-146] :sparkles: 애플 로그인 기능 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/service/OAuthAuthenticationProvider.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- src/test/java/com/stumeet/server/template/ApiTest.java
- 토큰 재발급 API 문서화 (성공)
- 토큰 재발급시 액세스 토큰이 만료된 상태라면 실패하는 버그 수정
- 테스트 종료시 레디스 컨테이너를 다시 사용할 수 없는 버그 수정
- Restdocs를 이용한 토큰 재발급 API 문서화
- 리프레시 토큰을 이용하여 유저 정보를 확인하도록 변경
- 각 테스트마다 레디스 컨테이너를 사용하도록 변경
> ✅ [STMT-146] 토큰 재발급 성공 테스트 추가

- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/OAuthLoginJpaEntity.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/main/java/com/stumeet/server/member/application/service/MemberAuthService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/JpaProfessionRepository.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionJpaEntity.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceAdapter.java
- src/main/java/com/stumeet/server/profession/adapter/out/persistence/ProfessionPersistenceMapper.java
- src/main/java/com/stumeet/server/profession/application/port/in/ProfessionQueryUseCase.java
- src/main/java/com/stumeet/server/profession/application/port/out/ProfessionQueryPort.java
- src/main/java/com/stumeet/server/profession/application/service/ProfessionQueryService.java
- src/main/java/com/stumeet/server/profession/domain/Profession.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1.1__insert_profession_data.sql
- src/main/resources/db/migration/V1__init.sql
- src/test/resources/application.yml
- 분야 정보를 대분류 / 소분류와 같은 형태로 관리하도록 변경
- flyway를 사용하여 DB를 형상관리하도록 변경
- 대분류 / 소분류를 관리하는 Schema 정의 및 도메인 모델링 진행
- 전달받은 id 값을 기준으로 분야를 조회하는 유즈케이스 추가
- ProfessionPersistenceMapper의 로직이 너무 더러운 것 같습니다 값이 NULL이 들어올 수도 있고(최초 소셜 로그인시 알 수 없기 때문에 NULL 값이 들어옴) parent의 값이 NULL일수도 있고 존재할 수도 있어서 변환로직이 더러운 것 같습니다. 이를 개선할 만한 방법이 있을까요?
> ✨ [STMT-146] 분야 정보를 관리하는 도메인 정의

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/common/token/JwtTokenProvider.java
- src/main/java/com/stumeet/server/common/token/repository/RefreshTokenRepositoryImpl.java
- src/main/java/com/stumeet/server/common/token/service/RefreshTokenService.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- 토큰 재발급 API 실패 응답에 대한 문서화 및 테스트 코드 작성
- API 문서에 Authorization Header에 Bearer 토큰 정보 누락
- API 문서에 Authorization Header에 Bearer 토큰 정보 추가하도록 변경
- 토큰 재발급 API에 실패 응답에 대한 문서화 및 테스트 코드 작성
> ✅ [STMT-146] 토큰 재발급 API 실패 응답 테스트 작성

- src/test/java/com/stumeet/server/common/auth/filter/LogoutFilterTest.java
- 로그아웃 테스트시 테스트가 실패하는 증상 발생
- 레디스 컨테이너가 띄워지지 않아 발생한 문제로 레디스 컨테이너를 띄워서 문제 해결
> :bug: [STMT-146] 로그아웃 API 테스트시 Redis 컨테이너를 띄우도록 변경

- build.gradle
- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/handler/ForbiddenAccessHandler.java
- src/main/java/com/stumeet/server/common/config/AwsS3Config.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberSignupCommand.java
- src/test/java/com/stumeet/server/helper/TestAwsS3Config.java
- src/test/java/com/stumeet/server/helper/WithMockMember.java
- src/test/java/com/stumeet/server/helper/WithMockMemberSecurityContextFactory.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberValidApiTest.java
- src/test/java/com/stumeet/server/profession/adapter/in/web/ProfessionQueryApiTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/template/ApiTest.java
- 최초 로그인시 회원가입 API 테스트 코드 작성 및 문서화
- 테스트시 S3에 계속 이미지가 올라가는 문제를 해결하기 위한 LocalStack 테스트 컨테이너 도입
- 시큐리티 인증 절차를 간결하기 위한 커스텀 어노테이션 @WithMockMember 정의 및 적용
-  최초 로그인시 회원가입 API 테스트 코드 작성 및 문서화
- 권한이 부족한 경우 ErrorCode를 사용하여 예외를 던지도록 리팩토링
- 회원가입 성공 Http Status 201 -> 200으로 변경
> ✅ [STMT-146] 최초 로그인 시 회원가입 API 테스트 코드 작성

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrImageFile.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrImageFileValidator.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrNotBlank.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrNotBlankValidator.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrPositive.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrPositiveValidator.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrValidSize.java
- src/main/java/com/stumeet/server/common/annotation/validator/NullOrValidSizeValidator.java
- src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
- src/main/java/com/stumeet/server/common/util/FileUtil.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberProfileApi.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberProfileUseCase.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberTokenUseCase.java
- src/main/java/com/stumeet/server/member/application/port/in/command/MemberProfileCommand.java
- src/main/java/com/stumeet/server/member/application/port/in/command/MemberSignupCommand.java
- src/main/java/com/stumeet/server/member/application/port/in/command/MemberUpdateCommand.java
- src/main/java/com/stumeet/server/member/application/port/in/command/TokenRenewCommand.java
- src/main/java/com/stumeet/server/member/application/port/out/MemberCommandPort.java
- src/main/java/com/stumeet/server/member/application/service/MemberProfileService.java
- src/main/java/com/stumeet/server/member/application/service/MemberTokenService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberProfileApiTest.java
- src/test/java/com/stumeet/server/member/application/service/MemberProfileServiceTest.java
- src/test/java/com/stumeet/server/stub/FileStub.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/ProfessionStub.java
> ✨ [STMT-90] 내 정보 수정 API 구현 (#72)

- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberJpaEntity.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceMapper.java
- src/main/java/com/stumeet/server/member/application/service/MemberOAuthService.java
- src/main/java/com/stumeet/server/member/domain/Member.java
- src/main/java/com/stumeet/server/member/domain/MemberLevel.java
- src/main/java/com/stumeet/server/member/domain/MemberRank.java
- src/main/resources/db/migration/V1.2__modify_member_level.sql
- src/test/java/com/stumeet/server/stub/MemberStub.java
- 당도 -> 레벨 변경으로 인한 스키마 수정 및 코드 대응
- 당도를 삭제하고 요구사항에 명시된 등급과 경험치를 사용하도록 변경하였습니다.
> :sparkles: [STMT-89] 당도 -> 레벨 변경으로 인한 스키마 구조 변경 및 코드 대응

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/auth/exception/IllegalKeyAlgorithmException.java
- src/main/java/com/stumeet/server/common/auth/exception/JwtInvalidSignatureException.java
- src/main/java/com/stumeet/server/common/auth/exception/JwtTokenParsingException.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/test/java/com/stumeet/server/common/auth/filter/OAuthAuthenticationFilterTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
- src/test/java/com/stumeet/server/stub/TokenStub.java
- 소셜 로그인시 JWT 토큰의 시그니처가 유효하지 않은 경우에 대한 메시지 핸들링 추가
- 기존 로직의 경우 Spring Security의 AuthenticationException을 이용하지 않아 정상적으로 핸들링이 되지 않는 문제가 존재하여 AuthenticationException을 상속하는 CustomException을 추가
> ✅ [STMT-146] 소셜 로그인시 전달한 JWT 토큰의 서명이 유효하지 않은 경우에 대한 핸들링 추가

- src/main/java/com/stumeet/server/common/auth/exception/IllegalKeyAlgorithmException.java
- src/main/java/com/stumeet/server/common/auth/exception/NotExistsOAuthProviderException.java
- src/main/java/com/stumeet/server/common/client/oauth/apple/AppleIdTokenProvider.java
- src/main/java/com/stumeet/server/common/exception/model/NotExistsException.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/member/adapter/out/persistence/MemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/member/domain/OAuthProvider.java
- src/main/java/com/stumeet/server/member/domain/exception/MemberNotExistsException.java
- 표준 예외를 사용하여 핸들링 되지 않았던 예외들을 커스텀 예외를 사용하도록 변경 필요
- 커스텀 예외를 이용하여 예외를 던지도록 변경했습니다.
- 특정 데이터가 존재하지 않는 예외에 대해 계층 구조를 만들었습니다. (BusinessException -> NotExistsException -> MemberNotExistsException)
- 도메인 관련 예외들은 domain 패키지에 exception이라는 하위 패키지를 만들었는데 어떻게 생각하시는지 궁금합니다. 
- 다음은 계층화된 커스텀 Exception의 예시입니다.
> :bug: [STMT-146] 표준 예외가 아닌 커스텀 예외를 사용하도록 변경

- src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
- src/main/java/com/stumeet/server/common/response/SuccessCode.java
- src/main/java/com/stumeet/server/dev/adapter/in/web/DevApi.java
- src/main/java/com/stumeet/server/dev/adapter/in/web/response/AccessTokenResponse.java
- src/main/java/com/stumeet/server/dev/application/service/DevService.java
- access token을 얻기 위해 매번 로그인을 하는 것이 번거롭습니다.
- dev용 access token 발급 api를 만들었습니다.
> ✨[STMT-6] DEV용 access token을 받아오는 api 작성

- .github/workflows/ci-cd.yml
- dev 브랜치에도 push가 발생해도 서버 배포를 진행하도록 변경
- 제어문을 제거하여 dev 브랜치에도 push가 발생하면 배포가 이루어지도록 처리했습니다.
> :construction_worker: [STMT-6] dev 브랜치에 push가 발생해도 서버 배포를 진행하도록 변경

- src/main/resources/db/migration/V1.4__add_study_table.sql
- 테이블 study_domain ddl 제약조건 설정 실수로 flyway의 실행에 오류가 있었습니다.
[이전 코드]
``` sql
`study_field_id` BIGINT NOT NULL COMMENT '스터디 분야 ID',
CONSTRAINT fk_study_field FOREIGN KEY (study_field_id)
REFERENCES study_field (id)
ON DELETE SET NULL ON UPDATE CASCADE
```
- 이전 코드에서 외래키 제약 조건을 삭제 시 null로 설정하게 해두었는데 외래키 필드가 not null로 설정되어 있어 문제가 발생했습니다.
- 해당 부분을 nullable로 선언하였습니다.
- 이전 코드는 요구사항에 딱 맞게 데이터 크기를 설정했는데, 변경하는 김에 크기를 조금씩 증가시켰습니다.
- 일반적으로 데이터 크기를 조금 여유있게 잡는 것은 데이터 무결성을 위해서 또는 미래의 요구사항 변경 시 데이터 크기 변경이 성능에 영향을 주기 때문이라고 합니다.
- 하지만 조금 고민이 되는게 만약에 (저의 잘못이겠지만) 예외처리가 잘못되어 스터디 인원에 50명 이상이 들어간다던가, 소개글, 규칙 등에 100자 이상이 들어갈 수 있는 가능성이 생기는 것이 걱정이 됩니다.
- DB로부터 에러가 발생하여 서버 에러 (Internal Exception)이 응답되는 것보다는 낫다고 생각하지만 이에 대해서 어떻게 생각하시는지 궁금합니다!
> :card_file_box: [STMT-220] 테이블 `study_domain` 외래키 제약조건 변경 및 각 필드 데이터 크기 증대

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/model/ApiResponse.java
- src/main/java/com/stumeet/server/common/response/SuccessCode.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepository.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberLeavePersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberLeaveUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberLeavePort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveService.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberLeaveApiTest.java
- src/test/java/com/stumeet/server/studymember/application/service/StudyMemberLeaveServiceTest.java
- 스터디 탈퇴 기능 구현
- 전달받은 스터디 아이디와 SecurityContext의 member ID를 가져와 회원 탈퇴 진행
> ✨ [STMT-193] 스터디 탈퇴 기능 구현

- src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityImagePersistenceMapper.java
- src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityParticipantPersistenceMapper.java
- src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityPersistenceMapper.java
- src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityImageJpaEntity.java
- src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityJpaEntity.java
- src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityParticipantJpaEntity.java
- src/main/java/com/stumeet/server/activity/application/port/in/command/ActivityConstructCommand.java
- src/main/java/com/stumeet/server/activity/domain/model/Activity.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityCategory.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityImage.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityLinkedStudy.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityMember.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityParticipant.java
- src/main/java/com/stumeet/server/activity/domain/model/Assignment.java
- src/main/java/com/stumeet/server/activity/domain/model/Default.java
- src/main/java/com/stumeet/server/activity/domain/model/Meet.java
- src/main/resources/db/migration/V1.5__create_activity_table.sql
-  활동 도메인과 영속 객체간 매핑이 필요함
- 추상 클래스인 활동을 구체 클래스로 생성할 수 있어야 함
- 데이터 저장을 위한 활동 스키마 정의
- 활동 카테고리 Enum을 이용한 팩토리 메서드 패턴 적용
- 활동 도메인과 영속화한 객체간 매핑 로직 추가
- flyway에 활동 스키마 내용 추가
- 활동 카테고리에 대한 Enum과 팩토리 메서드를 분리하는게 나을지 아니면 기존대로 유지해도 괜찮을지 찬미님의 의견이 궁금합니다 🤔
> ✨ [STMT-254] 활동 도메인과 영속 객체간 매핑 로직 작성

- .gitignore
- src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/study/adapter/in/web/StudyQueryApi.java
- src/main/java/com/stumeet/server/study/adapter/in/web/response/JoinedStudiesResponse.java
- src/main/java/com/stumeet/server/study/adapter/in/web/response/StudySimpleResponse.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/JpaStudyRepository.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/StudyPersistenceAdapter.java
- src/main/java/com/stumeet/server/study/adapter/out/persistance/mapper/StudyPersistenceMapper.java
- src/main/java/com/stumeet/server/study/application/port/in/StudyQueryUseCase.java
- src/main/java/com/stumeet/server/study/application/port/in/command/GetJoinedStudyCommand.java
- src/main/java/com/stumeet/server/study/application/port/in/mapper/StudyUseCaseMapper.java
- src/main/java/com/stumeet/server/study/application/port/out/StudyQueryPort.java
- src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
- src/main/java/com/stumeet/server/study/application/service/StudyUpdateService.java
- src/main/java/com/stumeet/server/study/domain/Study.java
- src/main/java/com/stumeet/server/study/domain/StudyField.java
- src/main/java/com/stumeet/server/study/domain/StudyStatus.java
- src/main/java/com/stumeet/server/study/domain/exception/StudyStatusNotExistsException.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberJoinService.java
- src/test/java/com/stumeet/server/stub/StudyStub.java
- src/test/java/com/stumeet/server/study/adapter/in/web/StudyQueryApiTest.java
- 가입 스터디 리스트 조회 API 구현
- 가입 스터디 리스트를 스터디 상태(`ACTIVE`, `FINISH`)를 기준으로 최신 가입 순으로 불러오는 API를 구현했습니다.
- status가 `FINISH`인 경우 스터디 히스토리를 불러오는 것으로 생각하고 있는데, 아직 구현은 하지 않았습니다.
- 커스텀 예외에서 예외 메시지를 지정하는 경우가 있는데, `NotExistsException`과 `InvalidStateException`의 경우 부모뿐만 아니라 커스텀 예외에 메시지가 따로 설정되어 있어도 출력되고 있지 않았습니다.
[이전 코드]
``` java
@ExceptionHandler(BadRequestException.class)
protected ResponseEntity<ApiResponse> handleCustomBadRequestException(final BadRequestException e) {
log.warn(ERROR_LOG_MESSAGE, e.getClass().getSimpleName(), e.getMessage());
String message = String.format("%s %s", e.getErrorCode().getMessage(), e.getMessage());
ApiResponse response = ApiResponse.fail(e.getErrorCode().getHttpStatusCode(), message);
return ResponseEntity.badRequest()
.body(response);
}
```
[변경 후 코드]
``` java …
```
> ✨ [STMT-268] 가입 스터디 리스트 조회 API 구현

- src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
- rest docs에 snippet을 custom하지 않으면 필수 정보인 optional을 표현할 수 없는 문제가 있었습니다.
- query-parameter의 커스텀 스니펫을 생성하고 optional 필드를 포함하도록 작성하였습니다.
https://docs.spring.io/spring-restdocs/docs/3.0.0/reference/htmlsingle/#documenting-your-api-customizing
> :memo: [STMT-11] rest docs query-parameters custom snippet 설정

- src/main/java/com/stumeet/server/common/token/service/RefreshTokenService.java
- src/main/java/com/stumeet/server/member/adapter/in/web/MemberAuthApi.java
- src/main/java/com/stumeet/server/member/adapter/in/web/response/TokenResponse.java
- src/main/java/com/stumeet/server/member/application/port/in/MemberTokenUseCase.java
- src/main/java/com/stumeet/server/member/application/service/MemberTokenService.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberAuthApiTest.java
리프레시 토큰 기한 만료 시 클라이언트에서 주기적으로 재로그인을 해야한다는 이슈가 있습니다.
앱을 지속적으로 사용하는 모바일 환경에서 단점이 될 수 있다고 생각하여 어세스 토큰 갱신 시 리프레시 토큰이 유효한 경우 리프레시 토큰도 갱신하는 방식으로 구현했습니다.
> ✨ [STMT-165] 어세스 토큰 갱신 시 리프레시 토큰도 갱신

- build.gradle
- 서버의 타임존이 UTC로 설정되어 있어 jwt 토큰의 만료 기한이 제대로 설정되지 않는 문제가 있었습니다.
- jib 설정의 환경변수에 타임존 설정을 추가했습니다.
> :rocket: [STMT-165] 서버 타임존 변경

- build.gradle
- 서버의 타임존이 UTC로 설정되어 있어 jwt 토큰의 만료 기한이 제대로 설정되지 않는 문제가 있었습니다.
- jib 설정의 jvmFlags에 타임존 설정을 추가했습니다.
> Stmt 165 set docker image timezone

- src/main/java/com/stumeet/server/ServerApplication.java
- src/main/java/com/stumeet/server/activity/adapter/out/event/handler/ActivityImageDeleteEventHandler.java
- src/main/java/com/stumeet/server/activity/adapter/out/event/model/ActivityImageDeleteEvent.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityImagePersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityImageCommandPort.java
- src/main/java/com/stumeet/server/common/config/EventConfig.java
- src/main/java/com/stumeet/server/common/event/EventPublisher.java
- src/main/java/com/stumeet/server/common/event/model/Event.java
- src/main/java/com/stumeet/server/study/application/service/ActivityImageDeleteService.java
- src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
활동을 삭제하는 상황에서 이미지 파일을 삭제하는 경우 외부 서비스인 S3에 요청해야 하기 때문에 딜레이가 생겼습니다.
- Spring Events 기능을 사용하여 활동 이미지 삭제 요청을 비동기로 요청하는 방식으로 구현했습니다.
> [STMT-262] 활동 이미지 일괄 삭제 비동기 이벤트로 구현

- src/main/java/com/stumeet/server/common/auth/config/SecurityConfig.java
- src/main/java/com/stumeet/server/member/application/service/MemberProfileService.java
- security 설정 때문에 FIRST_LOGIN 역할의 유저가 닉네임 유효성 검증에 접근하지 못하는 상황이 발생했습니다.
- spring security config에 해당 api path로 FIRST_LOGIN과 MEMBER 역할이 둘 다 접근할 수 있게 설정했습니다.
- 회원가입 API에 닉네임 유효성 검사 로직이 포함되어 있지 않아 추가했습니다.
> 🐛 [STMT-146] FIRST_LOGIN 역할의 유저가 닉네임 유효성 검증에 접근하지 못하는 에러 해결

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityJpaEntity.java
- src/main/java/com/stumeet/server/activity/application/port/in/command/ActivityCreateCommand.java
- src/main/java/com/stumeet/server/activity/application/port/in/mapper/ActivityUseCaseMapper.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityCreateService.java
- src/main/java/com/stumeet/server/activity/application/service/model/ActivityCreateSource.java
- src/main/java/com/stumeet/server/activity/domain/model/Activity.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityCategory.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityPeriod.java
- src/main/java/com/stumeet/server/activity/domain/model/Assignment.java
- src/main/java/com/stumeet/server/activity/domain/model/Default.java
- src/main/java/com/stumeet/server/activity/domain/model/Meet.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/resources/db/migration/V1.6__modify_activity_dates_nullable.sql
- src/main/resources/db/migration/V1.7__add_link_column_to_activity_table.sql
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityCreateApiTest.java
- src/test/java/com/stumeet/server/activity/application/service/ActivityCreateServiceTest.java
- src/test/java/com/stumeet/server/stub/ActivityStub.java
카테고리에 따른 스터디 활동 생성 방침의 변경으로 각 카테고리마다 필수 값이 달라져 해당 부분을 수정했습니다.
- 공통 필수값
- 활동유형
- 제목
- 내용
- 사진 
- 공지 등록 여부
- ASSIGNMENT 필수값
- 활동유형
- 제목
- 내용
- 시작일자
- 종료일자
- 참여멤버
- 사진
- 공지 등록 여부
- MEET 필수값
- 활동유형
- 제목
- 내용
- 시작일자
- 종료일자
- 장소
- 참여멤버
- 사진
- 공지 등록 여부
각 유형에 따라 필수 값을 검증하는 로직을 추가하고, 그에 따른 예외 처리를 추가로 작성했습니다.
유형에 따라 필드의 값이 null일수도 있기 때문에 request body 클래스에서는 nullable로 설정하고, 활동을 직접 생성할 때 각각의 생성자에서 값을 검증할 수 있도록 구현하였습니다.
> ✨[STMT-179] 활동 생성 request body 필드 필수 요청 값 수정 및 검증 로직 추가

- src/main/java/com/stumeet/server/activity/adapter/in/response/ActivityDetailResponse.java
- src/main/java/com/stumeet/server/activity/application/port/in/mapper/ActivityUseCaseMapper.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityAuthorityValidationService.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityQueryFacade.java
- src/main/java/com/stumeet/server/activity/domain/model/Activity.java
- src/main/java/com/stumeet/server/activity/domain/model/MeetStatus.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberValidationPort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberValidationService.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityQueryApiTest.java
- src/test/java/com/stumeet/server/activity/application/service/ActivityQueryFacadeTest.java
- src/test/java/com/stumeet/server/stub/ActivityStub.java
프론트에서 활동 상세 페이지의 삭제/수정 등의 권한 판단을 위한 플래그가 필요합니다.
활동 단일 조회 API DTO에 관련 속성을 추가했습니다.
- 작성자 여부: isAuthor
- 관리자 여부: isAdmin
추가적으로 요청받은 활동 상태값의 한글도 포맷팅했습니다.
> ✨ [STMT-184] 활동 단일 조회 API: 권한 확인 플래그 응답값 추가 및 활동 상태값 포맷팅

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/ActivityCreateApi.java
- src/main/java/com/stumeet/server/activity/application/port/in/ActivityCreateUseCase.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityCreateService.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityCreateApiTest.java
기획팀과의 논의에서 활동 생성 후 서버 API 호출 없이 프론트에서 자체적으로 활동 리스트에 업데이트하도록 기획이 변경되었습니다.
활동 생성 후 생성된 활동을 응답 값으로 반환하도록 구현했습니다.
> ✨ [STMT-179] 생성된 활동을 응답 값으로 반환하는 기능 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/common/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/stumeet/server/common/exception/model/BusinessException.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/main/java/com/stumeet/server/file/adapter/in/PresignedUrlGenerateWebAdapter.java
- src/main/java/com/stumeet/server/file/adapter/in/response/PresignedUrlResponse.java
- src/main/java/com/stumeet/server/file/adapter/in/response/PresignedUrlResponses.java
- src/main/java/com/stumeet/server/file/adapter/out/S3ImageStorageAdapter.java
- src/main/java/com/stumeet/server/file/application/port/in/PresignedUrlGenerateUseCase.java
- src/main/java/com/stumeet/server/file/application/port/in/command/PresignedUrlCommands.java
- src/main/java/com/stumeet/server/file/application/service/PresignedUrlGenerateAsyncService.java
- src/main/java/com/stumeet/server/file/application/service/PresignedUrlGenerateService.java
- src/test/java/com/stumeet/server/file/adapter/in/PresignedUrlGenerateWebAdapterTest.java
- src/test/java/com/stumeet/server/file/application/service/PresignedUrlGenerateAsyncServiceTest.java
- src/test/java/com/stumeet/server/file/application/service/PresignedUrlGenerateServiceTest.java
- src/test/java/com/stumeet/server/stub/FileStub.java
스터디의 활동을 생성할 때 최대 5개의 presigned url이 필요합니다.
업로드할 이미지의 개수만큼 요청을 하기보다는 복수의 url을 한번의 요청으로 발급하는 것이 효율적이라고 생각하여, 
업로드할 복수의 이미지 정보 목록을 받고 병렬로 presigned url 목록을 요청하는 방식으로 구현했습니다.
> ✨ [STMT-187] 복수의 presigned url 발급 API 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityParticipantPersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityParticipantRepository.java
- src/main/java/com/stumeet/server/activity/application/port/in/EvaluateMemberAchievementUseCase.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityParticipantQueryPort.java
- src/main/java/com/stumeet/server/activity/application/service/EvaluateMemberMemberParticipationService.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityParticipant.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivityStatus.java
- src/main/java/com/stumeet/server/activity/domain/model/AssignmentStatus.java
- src/main/java/com/stumeet/server/activity/domain/model/CommonStatus.java
- src/main/java/com/stumeet/server/activity/domain/model/DefaultStatus.java
- src/main/java/com/stumeet/server/activity/domain/model/MeetStatus.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustom.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/JpaStudyMemberRepositoryCustomImpl.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberQueryUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberDetailResponse.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberQueryPort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberQueryService.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApiTest.java
- 단일 스터디 멤버를 조회하는 API를 구현했습니다.
- 단일 스터디 멤버 조회 화면에서 참여한 활동 목록의 경우 멤버의 활동 리스트를 반환하는 API가 있으므로 멤버의 정보에 초점을 맞춰 구현했습니다.
- 응답 DTO
``` java
public record StudyMemberDetailResponse(
Long id,
String name,
String image,
String region,
String profession,
boolean canSendGrape,
Integer achievement
) {
}
```
스터디 멤버 목록 조회와 유사하지만, 요청자가 해당 멤버에게 포도알을 보낼 수 있는지 여부와 성취도가 추가됐습니다.
- 성취도 계산 로직
기획에서 제공한 수식으로 구현했습니다.
``` 
성취한 활동 (출석, 수행 상태만) / 활동 개수(모임, 과제) * 100
```
모임(Meet)의 인정결석의 경우 기획에 문의 결과 성취한 활동 개수에 포함하는 것으로 전달받아 결론적으로 `모임`의 출석, 인정결석, `과제`의 제출을 성취한 활동으로 포함했습니다.
- 활동 수행상태
- 공통
- 미참여
- 자유
- 없음
- 모임
- 시작 전
- 출석 ✅
- 결석
- 인정결석 ✅
- 지각
- 과제
- 시작 전
- 미제출
- 수행 ✅
- 미수행
- 멤버 상세 조회 화면
> ✨ [STMT-290] 단일 스터디 멤버 조회 API 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/ActivityQueryApi.java
- src/main/java/com/stumeet/server/activity/adapter/in/response/ActivityDetailResponse.java
- src/main/java/com/stumeet/server/activity/adapter/out/mapper/ActivityPersistenceMapper.java
- src/main/java/com/stumeet/server/activity/adapter/out/model/ActivityJpaEntity.java
- src/main/java/com/stumeet/server/activity/application/port/in/mapper/ActivityUseCaseMapper.java
- src/main/java/com/stumeet/server/bff/adapter/in/app/StudyHubApi.java
- src/main/java/com/stumeet/server/bff/adapter/in/app/StudyMemberHubApi.java
- src/main/java/com/stumeet/server/bff/adapter/in/app/response/StudyDetailFullResponse.java
- src/main/java/com/stumeet/server/bff/adapter/in/app/response/StudyMemberDetailFullResponse.java
- src/main/java/com/stumeet/server/study/application/service/StudyQueryService.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApi.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberQueryUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberAdminResponse.java
- src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberDetailResponse.java
- src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberGrapeResponse.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberQueryService.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityCreateApiTest.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityQueryApiTest.java
- src/test/java/com/stumeet/server/bff/adapter/in/app/StudyHubApiTest.java
- src/test/java/com/stumeet/server/bff/adapter/in/app/StudyMemberHubApiTest.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApiTest.java
- src/test/resources/db/setup.sql
UI에서 관리자만 보이는 옵션이 존재하여, 모든 API에 관리자 여부를 포함시키는 대신 이를 재사용 가능한 하나의 API로 통합했습니다.
하지만 이 방식은 멤버 또는 스터디 상세 화면에서 4~5개의 API 호출이 필요하게 되어, 통신 비용이 증가하고 효율성이 떨어지는 문제가 발생했습니다.
따라서 클라이언트의 환경에 따라 필요한 정보만을 뽑아주는 BFF(Backend For Frontend) 패턴을 차용하여 기존의 API는 그대로 두고, 화면에 필요한 정보를 통합으로 모아 응답하는 개념적으로 외부 API를 구현했습니다.
<div style="display: flex; justify-content: center; align-items: center; gap: 20px; width: 100%;">
</div>
> ✨ [STMT-295]  관리자 여부, 포도알 전송 가능 여부 판단 API 분리 및 멤버 상세 화면 통합 API 구현

- src/main/java/com/stumeet/server/notification/adapter/out/mapper/TopicSubscriptionPersistenceMapper.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/JpaTopicSubscriptionRepository.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/TopicPersistenceAdapter.java
- src/main/java/com/stumeet/server/notification/adapter/out/persistence/TopicSubscriptionPersistenceAdapter.java
- src/main/java/com/stumeet/server/notification/application/port/in/ManageSubscriptionUseCase.java
- src/main/java/com/stumeet/server/notification/application/port/out/TopicQueryPort.java
- src/main/java/com/stumeet/server/notification/application/port/out/TopicSubscriptionQueryPort.java
- src/main/java/com/stumeet/server/notification/application/service/ManageTopicService.java
- src/main/java/com/stumeet/server/notification/application/service/NotificationSendService.java
- src/main/java/com/stumeet/server/notification/application/service/RenewNotificationTokenService.java
- src/main/java/com/stumeet/server/notification/domain/TopicSubscription.java
기존에는 특정 기능(스터디 가입, 탈퇴 등)을 수행할 때 저장된 토큰을 사용하여 토픽을 구독했으나, 토큰이 갱신되는 경우 FCM 구독 정보가 최신 상태로 유지되지 않는 문제가 발생했습니다.
토큰 갱신 API를 호출할 때 새로운 토큰으로 FCM의 토픽 구독을 요청하여 토픽 구독 정보를 갱신하는 로직을 추가했습니다.
> :necktie: [STMT-300] 알림 토큰 갱신 시 멤버의 모든 토픽 구독 갱신

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/ParticipantStatusUpdateApi.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityParticipantPersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityParticipantRepository.java
- src/main/java/com/stumeet/server/activity/application/port/in/command/ParticipantStatusUpdateCommand.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityParticipantQueryPort.java
- src/main/java/com/stumeet/server/activity/application/service/ParticipantStatusUpdateService.java
- src/test/java/com/stumeet/server/activity/adapter/in/ParticipantStatusUpdateApiTest.java
- 멤버 활동 상태 변경 API에서 활동 멤버 조회 API에서 제공하지 않는 memberId를 사용하고 있었습니다.
- 클라이언트에서 요청을 원활하게 하도록 memberId를 요청에서 제거했습니다.
> :necktie: [STMT-264] 멤버 활동 상태 변경 API의 요청에서 조회 API에서 제공하지 않는 memberId 제거

- src/main/java/com/stumeet/server/member/adapter/in/web/MemberProfileApi.java
- src/main/java/com/stumeet/server/member/adapter/in/web/response/MemberProfileResponse.java
- src/main/java/com/stumeet/server/member/application/port/in/mapper/MemberUseCaseMapper.java
- src/main/java/com/stumeet/server/member/application/service/MemberProfileService.java
- src/main/java/com/stumeet/server/review/application/port/out/GrapeQueryPort.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/GrapePersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/repository/JpaGrapeRepository.java
- src/main/java/com/stumeet/server/studymember/application/port/in/MemberGrapeQueryUseCase.java
- src/main/java/com/stumeet/server/studymember/application/service/GrapeQueryService.java
- src/test/java/com/stumeet/server/member/adapter/in/web/MemberProfileApiTest.java
- src/test/java/com/stumeet/server/member/application/service/MemberProfileServiceTest.java
- src/test/java/com/stumeet/server/stub/MemberStub.java
멤버의 프로필을 조회하는 API 응답 값에 포도알 개수를 추가했습니다.
- MemberGrapeQueryUseCase에 포도알 개수를 쿼리하는 메서드를 구현했습니다.
- MemberProfileQueryService에서 해당 개수를 받아 응답으로 전송합니다.
- 기획 / ui 변경에 따른 변경을 방지하기 위해 `00 송이 00 개`가 아니라 포도알 개수 자체를 반환하도록 구현했습니다.
> ✨ [STMT-89] 멤버 프로필 조회 API 응답 값에 포도알 개수 추가

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/review/application/service/ReviewRegisterService.java
- src/main/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApi.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/StudyMemberPersistenceAdapter.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/entity/StudyMemberReview.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/repository/JpaStudyMemberRepositoryCustom.java
- src/main/java/com/stumeet/server/studymember/adapter/out/persistence/repository/JpaStudyMemberRepositoryCustomImpl.java
- src/main/java/com/stumeet/server/studymember/application/port/in/StudyMemberQueryUseCase.java
- src/main/java/com/stumeet/server/studymember/application/port/in/response/StudyMemberReviewStatusResponse.java
- src/main/java/com/stumeet/server/studymember/application/port/out/StudyMemberQueryPort.java
- src/main/java/com/stumeet/server/studymember/application/service/StudyMemberQueryService.java
- src/test/java/com/stumeet/server/stub/ReviewStub.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/LegacyStudyHideApiTest.java
- src/test/java/com/stumeet/server/studymember/adapter/in/web/StudyMemberQueryApiTest.java
- src/test/resources/db/setup.sql
- 사용자에게 특정 스터디에서 리뷰를 작성하지 않은 스터디 멤버의 목록을 조회할 필요성이 있었습니다.
- 로그인한 멤버를 기준으로 특정 스터디의 멤버 리뷰 상태 목록을 조회하는 API를 구현했습니다.
> ✨ [STMT-314] 특정 멤버 기준의 스터디 멤버 리뷰 상태 목록 조회 API 구현

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/activity/adapter/in/ActivityQueryApi.java
- src/main/java/com/stumeet/server/activity/adapter/in/converter/ActivityCategoryConverter.java
- src/main/java/com/stumeet/server/activity/adapter/in/converter/ActivitySortConverter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/ActivityPersistenceAdapter.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityRepositoryCustom.java
- src/main/java/com/stumeet/server/activity/adapter/out/persistence/JpaActivityRepositoryCustomImpl.java
- src/main/java/com/stumeet/server/activity/application/port/in/ActivityQuery.java
- src/main/java/com/stumeet/server/activity/application/port/in/query/ActivityListBriefQuery.java
- src/main/java/com/stumeet/server/activity/application/port/in/query/ActivityListDetailedQuery.java
- src/main/java/com/stumeet/server/activity/application/port/out/ActivityQueryPort.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityQueryFacade.java
- src/main/java/com/stumeet/server/activity/application/service/ActivityQueryService.java
- src/main/java/com/stumeet/server/activity/domain/exception/NotExistsActivitySortException.java
- src/main/java/com/stumeet/server/activity/domain/model/ActivitySort.java
- src/main/java/com/stumeet/server/common/response/ErrorCode.java
- src/test/java/com/stumeet/server/activity/adapter/in/ActivityQueryApiTest.java
기획 변경으로 홈 화면에서 조회되는 활동 목록 간략/상세 조회 API에서 기존에 지원하지 않던 복수 카테고리 선택과 `최신순`, `각 유형 기준순` 정렬이 필요해졌습니다.
- `ActivitySort` Enum 클래스를 추가하여 최신순, 각 유형기준순 정렬을 정의했습니다.
- QueryDsl의 CaseBuilder를 사용하여 category별 정렬 기준을 적용했습니다.
- 기존 쿼리 조회 기준을 리팩터링 했습니다.
- Spring Enum Converter를 구현하여 `ActivityCategory`와 `ActivitySort` 변환과 예외를 처리했습니다.
- 명세서
https://stumeet.shop/docs/index.html#_%EC%8A%A4%ED%84%B0%EB%94%94_%ED%99%9C%EB%8F%99_%EC%83%81%EC%84%B8_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C
https://stumeet.shop/docs/index.html#_%EC%8A%A4%ED%84%B0%EB%94%94_%ED%99%9C%EB%8F%99_%EA%B0%84%EB%9E%B5_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C
> ✨ [STMT-187] 활동 목록 간략/상세 조회 API: 복수 카테고리 선택, 정렬 기준 추가

- src/main/java/com/stumeet/server/review/adapter/out/persistence/JpaReviewTagRepository.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/ReviewPersistenceAdapter.java
- src/main/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApi.java
- src/main/java/com/stumeet/server/review/adapter/out/web/dto/ReviewStatsResponse.java
- src/main/java/com/stumeet/server/review/application/port/in/ReviewQueryUseCase.java
- src/main/java/com/stumeet/server/review/application/port/out/ReviewQueryPort.java
- src/main/java/com/stumeet/server/review/application/service/ReviewQueryService.java
- src/test/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApiTest.java
- UI의 리뷰 통계 퍼센트 게이지 산출을 위해 리뷰 태그의 총 개수가 필요했습니다.
- 리뷰 통계 조회 API 응답에 태그 총 개수를 추가했습니다.
> ✨ [STMT-307] 리뷰 통계 조회 API 응답에 태그 총 개수 필드 추가

- src/main/resources/application-prod.yml
- AWS elastic cache의 valkey 연결 시 time out 에러 발생
- 암호화 설정이 활성화 되어 있기 때문에 spring redis 설정에 ssl을 활성화
> fix: elastic cache valkey 연결 ssl 설정

- src/docs/asciidoc/index.adoc
- src/main/java/com/stumeet/server/review/adapter/out/persistence/JpaReviewRepositoryCustom.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/JpaReviewRepositoryCustomImpl.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/ReviewPersistenceAdapter.java
- src/main/java/com/stumeet/server/review/adapter/out/persistence/mapper/ReviewPersistenceMapper.java
- src/main/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApi.java
- src/main/java/com/stumeet/server/review/adapter/out/web/dto/ReviewDetailResponses.java
- src/main/java/com/stumeet/server/review/application/port/in/ReviewQueryUseCase.java
- src/main/java/com/stumeet/server/review/application/port/out/ReviewQueryPort.java
- src/main/java/com/stumeet/server/review/application/service/ReviewQueryService.java
- src/test/java/com/stumeet/server/review/adapter/out/web/ReviewQueryApiTest.java
- 유저 리뷰 상세 목록 조회 API가 페이지네이션 방식으로 구현되어 있었는데 페이지 정보가 제공되지 않는 문제가 있었습니다.
- Page 목록을 조회하도록 수정하고, 응답에 pageinfo를 추가했습니다.
> :recycle: [STMT-307] 유저 리뷰 상세 목록 조회 API 응답 결과를 페이지네이션으로 리팩터링
